<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<UseWindowsForms>true</UseWindowsForms>
	<ApplicationIcon>MyWidget.ico</ApplicationIcon>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <InformationalVersion>1.0.0</InformationalVersion>
    <Product>MyButtonsWidget</Product>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\fon1.jpg" />
    <None Remove="Images\fon2.jpg" />
    <None Remove="Images\fon3.jpg" />
    <None Remove="MyWidget.ico" />
    <None Remove="Videos\video1.mp4" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="MyWidget.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Images\" />
    <Folder Include="Videos\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="MyWidget.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
